apiVersion: v1 
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: recommendation
  ports:
  - port: 1010
    targetPort: 1010
    protocol: TCP
