apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-demo-productcatalogservice

  labels:
    app: product-catalog

spec:
  replicas: 2
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: product-catalog

  template:
    metadata:
      labels:
        app: product-catalog

    spec:
      serviceAccountName: opentelemetry-demo

      containers:
      - name: product-catalog

        image: vpk1999/ultimate_devops_project:product-catalog-v2

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8088

        env:
        - name: PRODUCT_CATALOG_PORT
          value: "8088"

        - name: OTEL_SERVICE_NAME
          value: "productcatalogservice"

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-demo-otelcol:4317"

        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=productcatalogservice"

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-productcatalogservice

spec:
  type: ClusterIP

  selector:
    app: product-catalog

  ports:
  - port: 8080
    targetPort: 8088